Refine messages + hier/perms checks
Sorry for this "foo" commit :-D

diff --git a/kianidraw-new b/kianidraw-new
--- a/kianidraw-new
+++ b/kianidraw-new
@@ -1,6 +1,5 @@
 #!/bin/sh
 PROG_NAME=$(basename $0)
-MSG_PREFIX=$PROG_NAME
 INTERNAL_IN=.kianidraw/in
 EXTERNAL_IN=in
 
@@ -10,9 +9,9 @@ test -n "$1" || {
 }
 
 mkdir "$1" 2>/dev/null || {
-	echo "$MSG_PREFIX: \"$1\": cannot create this project here" >&2
+	echo "$PROG_NAME: \"$1\": cannot create this project here, please check permissions" >&2
 	exit 1
 }
 
 cd "$1"
-mkdir -p $INTERNAL_IN $EXTERNAL_IN && echo "$MSG_PREFIX: created project \"$1\""
+mkdir -p $INTERNAL_IN $EXTERNAL_IN && echo "$PROG_NAME: created project \"$1\""
diff --git a/kianidraw-update b/kianidraw-update
--- a/kianidraw-update
+++ b/kianidraw-update
@@ -4,16 +4,16 @@ MSG_PREFIX="$PROG_NAME[$(basename "$(pwd)")]"
 INTERNAL_IN=.kianidraw/in
 
 exit_bad_location() {
-	echo "$PROG_NAME: not in a valid/usable kianidraw project" >&2
+	echo "$PROG_NAME: not in a valid/usable kianidraw project, please cd and/or check permissions" >&2
 	exit 1
 }
 
-for flag in d r w x; do
-	test -$flag $INTERNAL_IN || exit_bad_location
-done
+test -d $INTERNAL_IN || exit_bad_location
+find . -type d -exec chmod u+rwx {} \; || exit_bad_location
+find . -type f -exec chmod u+rw  {} \; || exit_bad_location
 
 test -n "$1" || {
-	echo "$MSG_PREFIX: at least 1 arg required: all|(<resourceName>)..." >&2
+	echo "$MSG_PREFIX: at least 1 arg required: all|<resourceName>..." >&2
 	exit 64
 }
 
