Use docopt notation

diff --git a/kianidraw-import b/kianidraw-import
--- a/kianidraw-import
+++ b/kianidraw-import
@@ -21,7 +21,7 @@ test X"$1" = X"-m" && {
 }
 
 test -n "$1" || {
-	echo "$MSG_PREFIX: at least 1 arg required: file [other files]" >&2
+	echo "$MSG_PREFIX: at least 1 arg required: <file>..." >&2
 	exit 64
 }
 
diff --git a/kianidraw-new b/kianidraw-new
--- a/kianidraw-new
+++ b/kianidraw-new
@@ -4,7 +4,7 @@ MSG_PREFIX=$PROG_NAME
 
 
 test -n "$1" || {
-	echo "$PROG_NAME: 1 arg required: projectName" >&2
+	echo "$PROG_NAME: 1 arg required: <projectName>" >&2
 	exit 64
 }
 
