Use uniformized style for messages

diff --git a/kianidraw-edit b/kianidraw-edit
--- a/kianidraw-edit
+++ b/kianidraw-edit
@@ -20,7 +20,7 @@ test -n "$1" || {
 cd $INTERNAL_IN
 
 test -f "$1".xcf || {
-	echo "$MSG_PREFIX: resource \"$1\" not found" >&2
+	echo "$MSG_PREFIX: \"$1\": resource not found" >&2
 	exit 1
 }
 
diff --git a/kianidraw-new b/kianidraw-new
--- a/kianidraw-new
+++ b/kianidraw-new
@@ -10,7 +10,7 @@ test -n "$1" || {
 }
 
 mkdir "$1" 2>/dev/null || {
-	echo "$MSG_PREFIX: cannot create project \"$1\" here" >&2
+	echo "$MSG_PREFIX: \"$1\": cannot create this project here" >&2
 	exit 1
 }
 
diff --git a/kianidraw-update b/kianidraw-update
--- a/kianidraw-update
+++ b/kianidraw-update
@@ -25,7 +25,7 @@ for arg; do
 		to_update="$to_update $(find . -maxdepth 1 -type l | sed 's/^\.\///')"
 	else
 		test -f "$arg".xcf || {
-			echo "$MSG_PREFIX: warning: resource \"$arg\" not found" >&2
+			echo "$MSG_PREFIX: warning: \"$arg\": resource not found" >&2
 			continue
 		}
 		to_update="$to_update $arg"
