Finish k-update implementation

diff --git a/kianidraw-update b/kianidraw-update
--- a/kianidraw-update
+++ b/kianidraw-update
@@ -25,15 +25,37 @@ for arg; do
 		to_update="$to_update $(find . -maxdepth 1 -type l | sed 's/^\.\///')"
 	else
 		test -f "$arg".xcf || {
-			echo "$MSG_PREFIX: warning: \"$arg\": resource not found" >&2
+			echo "$MSG_PREFIX: warning: \"$arg\": resource not found => skipped" >&2
 			continue
 		}
 		to_update="$to_update $arg"
 	fi
 done
 
+convert_xcf_to_pngs() {
+	infile=$1
+	outfiles_dir=$2
+
+	{
+		cat <<END
+def convert(infile, outfiles_dir):
+	img = pdb.gimp_file_load(infile, infile)
+	for layer in img.layers:
+		outfile = outfiles_dir + "/" + layer.name + ".png"
+		print(layer.name)
+		pdb.gimp_file_save(img, layer, outfile, outfile)
+	pdb.gimp_image_delete(img)
+END
+		echo "convert(\"$infile\", \"$outfiles_dir\")"
+		echo "pdb.gimp_quit(1)"
+	} | gimp -i --batch-interpreter=python-fu-eval -b -
+}
+
 for u in $to_update; do
 	echo $u
 done | uniq | while read resource; do
-	echo $resource
+	echo "$MSG_PREFIX: processing elements for \"$resource\"…"
+	mkdir -p $resource.d
+	rm -f $resource.d/*
+	convert_xcf_to_pngs $resource.xcf $resource.d
 done
